### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by ghost** [ObelusFamily/Anythink-Market-ptfjzn2o#2]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by jessitron** [comment]
I hate this issue SO MUCH

Tell me how to REPRODUCE THE BUG

What is "creating a new product" ??? HOW DO I DO THAT

**Comment by jessitron** [comment]
also, I made a guess, and the New Item screen doesn't work at all; "Publish Item" gives me a JS error in the console that I can't interpret
